### ISSUE TITLE
dependencies list

### ISSUE THREAD

**Issue by sbenthall** [codeforamerica/gotissues#1]
It would be helpful to have a requirements.txt file or something for dependencies.

based on the current README instructions I've made a new virtual env and tried to run app.py, installing the modules by hand to solve each ImportError. But now I'm getting this:

```
(gotissues)sb@arcadia:~/projects/gotissues$ python app.py 
Traceback (most recent call last):
  File "app.py", line 7, in <module>
    from apiclient.errors import HttpError
ImportError: No module named errors
```

even though i've pip installed apiclient. Stumped for now.

**Comment by tmaybe** [comment]
hey @sbenthall, the library you want is google-api-python-client not apiclient. I made a branch here with a requirements.txt file that should install everything you need:

https://github.com/codeforamerica/gotissues/tree/make-setup-easier

**Comment by ondrae** [comment]
I've cleaned up the installation instructions
