### ISSUE TITLE
Clean up run.py

### ISSUE THREAD

**Issue by eunicekokor** [codeforamerica/gotissues#14]
Maybe would be easier to access all the analytics data from  `run.py` if we stored the results from each method in a dictionary or something like that.

[This line](https://github.com/codeforamerica/gotissues/blob/master/run.py#L293) was getting pretty long and it will make it easier to combine /tests and /index and hopefully I might want to also organize the methods better since I sometimes find myself wasting time

**Comment by ondrae** [comment]
Let s do this right away to save our sanity.

A suggested structure:

```
/gotissues
  gotissues.py - the core of gotissues, it should pull in functions from the others
  views.py - All of the routes
  data_helpers.py - Everything that pulls in data from GAnalytics, Github, and the database.
  view_helpers.py - Helper functions for the views
  daily_update.py - separate script pulling mostly from data_helpers.py
  /scripts - All of the sql scripts
  /tests  - test scripts and test data
```

**Comment by eunicekokor** [comment]
Sounds great! I'm looking through #15, and yeah I like that file structure.
