### ISSUE TITLE
What next?

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/gotissues#3]
I've added some [sample data](https://github.com/codeforamerica/gotissues/blob/master/sample-google-analytics.json) from google analytics.

What are some first inquiries we should make?
- How many total clicks?
- How many different issues?
- How many clicked issues are now closed?
- How many clicked issues were commented on?
- How many people not involved in that project or Brigade, interacted with the issue?
- What kind of issues get clicked on the most? Closed the most? Commented on the most?

**Comment by ondrae** [comment]
@sbenthall This [sample data](https://github.com/codeforamerica/gotissues/blob/master/sample-google-analytics.json) is a great place to start your analysis.

**Comment by ondrae** [comment]
What percentage of views get clicks?

**Comment by sbenthall** [comment]
Here is a first look at the sample data you've provided. It's a simple plot of each issue in descending order of number of clicks.

![sample-data-plot](https://cloud.githubusercontent.com/assets/68752/8158305/a8cb2e68-1364-11e5-950e-d438d3e3328c.png)

The first thing I notice when I look at this is that the distribution of clicks is very uneven. The data does not include issues that were never clicked at all.

A good first question would be "Why are some issues clicked many times, and why are some not clicked at all?" The first place I would look is the user interface. Does the Civic Tech Issue Finder display issues in a consistent order, always putting some towards the top? What are other explanations? 

I expect a deeper look at the Google Analytics data would answer these questions.

**Comment by ondrae** [comment]
We've got the number of views for each issue included in the upcoming api for you @sbenthall 
https://github.com/codeforamerica/gotissues/issues/5#issuecomment-119006688
