### ISSUE TITLE
Front page modifications

### ISSUE THREAD

**Issue by eunicekokor** [codeforamerica/gotissues#31]
Displaying what we learned a little better on http://got-issues.herokuapp.com.

To make the 'Event' counts more informative, we can have a side area for each that has word frequency/word cloud results for the titles or the tags (excluding 'help wanted' of course) and maybe average # of words in descriptions (if it's not too much of a hassle)

for example it will be like 127 Pull Requests --> Common Title Words, Common Tags, Avg # of comments
From there it will also be helpful to Brigades making better issues, like if they want more Pull Requests coming in, they should use some of the words/tags that are common that we displayed. And we can talk about how comments affect or don't effect the number of PRs you get etc. etc. etc. Let me know what else to add @ondrae!

**Comment by eunicekokor** [comment]
On the [front page branch](https://github.com/codeforamerica/gotissues/tree/front-page-%2331)!

**Comment by ondrae** [comment]
Checked it out. Looks good. I like the rocket badges.

Thats a good idea to start checking out common attributes of the Github activity that we want. 

We could get real choosy about the github activity we care about, dropping the ones we dont.

**Comment by eunicekokor** [comment]
Alright! I just pushed my latest for getting frequent titles, the only thing is that it takes about 60 seconds to load the page each time, since it needs to make a database query for each Event, so I'm in the process of making a new db with 
`activity_type` `common_titles` `common_labels` `avg_desc_length` ++ anything else we think is important.

**Comment by ondrae** [comment]
So good! You've done a great job in getting some of these complicated ideas easy to understand in a glance. You've really got a talent for it. Great work.

Next we'll want to get rid of the events we dont think are important anymore, like the IssuesEvent and the GollumEvent. They are just kind of distracting. 

Digging into the labels and titles is going to be interesting. Lets see what you can find.

**Comment by eunicekokor** [comment]
Thank you! Sounds good, I'll try to merge this tonight!
