### ISSUE TITLE
Problems getting refreshed access_token to views

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/gotissues#41]
#### Description

I had upped the dynos on our Heroku instance to the Hobby level. This would make the page load faster as it would never sleep. I checked it this morning and the javascript was giving errors about needing to login.

There is some disconnect between refreshing the access_token and letting our javascript have access to it.
#### To Reproduce

Start up your local server and let it run for an hour. Reload the page and the javascript will fail.

**Comment by eunicekokor** [comment]
Hmmm this is weird, trying it out now!

**Comment by eunicekokor** [comment]
do our javascript elements stop loading? what do the error messages say?
