### ISSUE TITLE
Issue gardener icon

### ISSUE THREAD

**Issue by migurski** [codeforamerica/gotissues#47]
Can we use [the lawnmower man](https://en.wikipedia.org/wiki/The_Lawnmower_Man_%28film%29) as an icon?

![lawnmower man](http://www.empireonline.com/images/uploaded/pierce-brosnan-the-lawnmower-man.jpg)

**Comment by ondrae** [comment]
Which one?
![screen shot 2015-07-28 at 4 14 14 pm](https://cloud.githubusercontent.com/assets/595778/8946261/e4e9e7bc-3543-11e5-922b-7c4ec19e1bd9.png)
or 
![screen shot 2015-07-28 at 4 14 21 pm](https://cloud.githubusercontent.com/assets/595778/8946268/ecf480ac-3543-11e5-9a56-a952bbb2f852.png)

No

**Comment by migurski** [comment]
Hm okay. :(
