### ISSUE TITLE
Make new endpoints to expose data

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/gotissues#5]
#### Description

We need to make some new endpoints where we can access the raw data. We're still not sure what data will be useful, as this is still an experiment. Start with the three queries we already have.
#### Example

`https://got-issues.herokuapp.com/top_ten_clicked_issues`

```
[
  {
    "issue" : "https://github.com/GSA/data.gov/issues/464",
    "clicks" : 71
  } ,
  ...
]
```
#### Files

run.py
#### Tasks

Make a new endpoints for:
- [ ] Total clicks
- [ ] Top Ten Clicked Issues
- [ ] Most recently clicked issue
- [ ] Tests

**Comment by sbenthall** [comment]
Re: "Top Ten Clicked Issues", see https://github.com/codeforamerica/gotissues/issues/3#issuecomment-112017032

I think this data would be more meaningful if it was normalized somehow against its prominence on the Civic Issue Finder site. So a good endpoint (if it can be collected from Google Analytics...maybe it would require some hacking on the UI to get GA to pick it up) would be "Number of times issues have been displayed on the front page (and in what order)."

**Comment by eunicekokor** [comment]
Another related thing I realized, too, was that some issues are getting more face time on some sites. For example, only SF Brigade projects are shown on the Code for San Fransisco page, so it might be useful to look at the number of times the issue has been displayed on each page the widget exists if also possible?

**Comment by migurski** [comment]
:+1: @eunicekokor

**Comment by ondrae** [comment]
We've got some database tables set up with the data we think to be useful.

We can expose these through an api for @sbenthall to do some analysis with.

`/issues`

```
{
"html_url": "https://github.com/codeforamerica/gotissues/issues/8",
  "id": 87136867,
  "title": "Pull in data from GitHub about the clicked issues",
  "labels": [
    { "url": "https://api.github.com/repos/codeforamerica/gotissues/labels/enhancement",
      "name": "enhancement",
      "color": "84b6eb"
    }
  ],
  "state": "closed",
  "comments": 1,
  "created_at": "2015-06-10T23:03:05Z",
  "closed_at": "2015-06-23T00:43:26Z",
  "body": "TEST BODY",
  "closed_by": {
    "login": "ondrae",
    "id": 595778
  },
  "clicks" : 10000000,
  "views" : 777,
  "view_sources" : ["www.codeforamerica.org","http://testurl.com"]
}
```

and
`/activity`

```
{
  "issue_url": "https://github.com/codeforamerica/gotissues/issues/8",
  "click_timestamp": "2015-12-27 07:30:00",
  "activity_type": "PushEvent",
  "activity_timestamp": "2015-06-06 23:16:56"
}
```
