### ISSUE TITLE
Add some realtime data 

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/gotissues#6]
#### Description

Lets make the issue finder analytics more interesting to look at. We get enough traffic that there is usually someone interacting with the issue finder. Lets add some real time analytics. 
#### Data
- Visitors on site
- Recent clicks
- Where they are on a map
#### Files

run.py
templates/index.html
https://developers.google.com/analytics/devguides/reporting/realtime/v3/

**Comment by apranav19** [comment]
Hi there,
Regarding the geographical data, is there a mapping library that you have in mind? I was thinking of using Google Maps' API.

**Comment by ondrae** [comment]
Hey @apranav19. We've put this issue on hold as we are answering some other questions about the data. I'll close it so that others dont get distracted by it.
