### ISSUE TITLE
how should scientific results get included in the repository?

### ISSUE THREAD

**Issue by sbenthall** [codeforamerica/gotissues#9]
Thank you for including some sample data to get started with in #3 

I'm wondering how best to included scientific results in this repository (or in a new, related repository).

One option is to use [Jupyter](https://jupyter.org/) (formerly I Python) notebooks, for which GitHub now has support for in-browser rendering. I would recommend this.

A related issue is how to include scientific Python dependencies, such as numpy and matplotlib. These tend to have large C dependencies and can be a pain to install. Is that overhead acceptable?

An alternative would be to use the [Anaconda ](https://store.continuum.io/cshop/anaconda/) Python distribution. This makes it easier to install scientific Python packages, but would be a departure from the CfA virtualenv workflow.

An example of a project that has been trying to use Conda, as well as support Virtualenv, so that Jupyter notebooks can be included in the project is [BigBang](https://github.com/sbenthall/bigbang). Architecturally, it is definitely not perfect. Is there a better way?

**Comment by sbenthall** [comment]
Lighter weight alternatives:
- analysis and/or scientific discussion can just stay on the issue tracker or,
- they can go on the wiki

**Comment by ondrae** [comment]
Hi Sebastian, good to see you here again. I'm on the road today so will be brief, yet I would say you should work however you are most comfortable. We'll figure out the right way to include what you learn as it progresses.

**Comment by sbenthall** [comment]
Sounds good. Will do.

**Comment by ondrae** [comment]
Hi @sbenthall 

How would you like to access fresh data?
- Flat files on S3
- Access to a database
- An API

What kind of data would you like? A baseline will be:
- Clicked GitHub urls
- Number of clicks for that url
- Number of views for that url starting today with this [pull request](https://github.com/codeforamerica/civic-issue-finder/pull/35)

Is the github url enough for you to then go a collect all of the timestamps you need? @eunicekokor is starting work on collecting [Activity](https://github.com/codeforamerica/gotissues/milestones/Exploring%20Activity) on clicked issues. That can all be made available to you as well once ready.

**Comment by ondrae** [comment]
We'll build an api for getting the issue data and the activity data.
https://github.com/codeforamerica/gotissues/issues/5#issuecomment-119006688
